name: opentelemetryapp
services:
  seq:
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    # volumes:
    #   - ./seq-data/:/data
    ports:
      - 5341:80
    image: datalust/seq
